Print("======================================");
kill(all);
print("sec 12, ex-9");

w(x,t):=cos(0.017*t-0.656*x)*%e^(-0.656*x);
float(w(4,0));


Print("======================================");
kill(all);
print("sec 12.8");

x:[30,45,60,75,90,100];
y:[5270,5680,6250,7210,8200,8710];
Sx:sum(x[i],i,1,6);
Sy:sum(y[i],i,1,6);
Sxy:sum(x[i]*y[i],i,1,6);
Sxs:sum((x[i])^2,i,1,6);
m:float((Sx*Sy-6*Sxy)/((Sx)^2-6*Sxs));
b:float(1/6*(Sy-m*Sx));
